# -*- coding: utf-8 -*-
"""Segragation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KFNMxW8qLKcCO0VMdhtHyekSIRqXbKX
"""

# Installing the ace_tools module
!pip install ace_tools

# importing the necessary libraries
import pandas as pd
from ace_tools import display_dataframe_to_user

# Loading the dataset
df = pd.read_csv('/content/sample_data/Math_dataset2.csv')

# Pivoting to separate questions and answers
df_segregated = (
    df.pivot_table(
                    index='conversation_id',
                    columns='message_type',
                    values='message',
                    aggfunc='first').reset_index().rename(columns={'input': 'question',
                                                                   'output': 'answer'}))

# Saving the result to a new CSV file
df_segregated.to_csv('Math_dataset2_segregated.csv', index=False)

# Displaying a preview of the segregated DataFrame
display_dataframe_to_user('segregated_preview', df_segregated.head())